module Y2017.M05.D17.Exercise where

{--
Another projecteuler.net problem? Sure.

Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value 
of D?
--}

-- gives the nth pentagon number:

pent :: Integer -> Integer
pent n = undefined

-- gives n from the pentagon number p, or nothing if p is not a pentagon number

copent :: Integer -> Maybe Integer
copent p = undefined

-- D = | Pk - Pj |, for Pentagon numbers, Pk, Pj, such that Pk + Pj is pentagon
-- and | Pk - Pj | is pentagon.

ds :: [Integer]
ds = undefined
